name: Cloud Storage Uploader

on:
  push:
    branches:
      - master  # Runs when code is pushed to the master branch

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: checkout
      uses: actions/checkout@v4

    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: upload-styles-folder
      uses: google-github-actions/upload-cloud-storage@v2
      with:
        path: './Public/Styles'
        destination: 'jandy-dev-images'
        gzip: false
        headers: |-
          content-type: 'text/css'
        

    - id: upload-javascript-folder
      uses: google-github-actions/upload-cloud-storage@v2
      with:
        path: './Public/Javascript'
        destination: 'jandy-dev-images'
        gzip: false
        headers: |-
          content-type: 'application/javascript'
