name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Runs when code is pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the build runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/jandy-app:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/jandy-app:latest
